services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketplace-profile-php-fpm
    restart: unless-stopped
    volumes: 
     - ./:/var/www/marketplace-profile
    extra_hosts:
      - "172.17.0.1:host-gateway"
    env_file:
      - .env.dev
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - marketplace-profile-network

  nginx:
    image: nginx:alpine
    container_name: marketplace-profile-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./:/var/www/marketplace-profile
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    environment:
      TZ: "Europe/London"
    networks:
      - marketplace-profile-network

  postgres:
    image: postgres:17-alpine
    container_name: marketplace-profile-postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    networks:
      - marketplace-profile-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: marketplace-profile-rabbitmq
    restart: unless-stopped
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_PANEL_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    networks:
      - marketplace-profile-network

networks:
  marketplace-profile-network:
    driver: bridge

volumes:
  postgres-data:
