services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketplace-profile-php-fpm
    restart: unless-stopped
    volumes: 
     - ./:/var/www/app
    networks:
      - marketplace-profile-network
    environment:
      APP_ENV: ${APP_ENV}
      MESSENGER_TRANSPORT_DSN: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:${RABBITMQ_PORT}/%2f/messages
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?serverVersion=16&charset=utf8
      XDEBUG_CONFIG: "client_host=172.17.0.1"
    extra_hosts:
      - "172.17.0.1:host-gateway"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: marketplace-profile-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    environment:
      TZ: "Europe/London"
    networks:
      - marketplace-profile-network

  postgres:
    image: postgres:17-alpine
    container_name: marketplace-profile-postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    networks:
      - marketplace-profile-network

  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: marketplace-profile-rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - marketplace-profile-network

networks:
  marketplace-profile-network:
    driver: bridge

volumes:
  postgres-data:
