services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: users-php-fpm
    restart: unless-stopped
    # volumes: 
    #   - ./:/var/www/identity # for dev
    extra_hosts:
      - "172.17.0.1:host-gateway"
    env_file:
      - .env.dev
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - ls-users-network

  nginx:
    image: nginx:alpine
    container_name: users-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./:/var/www/identity
      - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    environment:
      TZ: "Europe/London"
    networks:
      - ls-users-network

  postgres:
    image: postgres:17-alpine
    container_name: users-postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    networks:
      - ls-users-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: users-rabbitmq
    restart: unless-stopped
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_PANEL_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    networks:
      - ls-users-network

  mailer:
    image: axllent/mailpit
    container_name: users-mailer
    restart: unless-stopped
    ports:
      - "${MAILER_PORT}:1025"
      - "${MAILER_PANEL_PORT}:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      TZ: "Europe/London"
    networks:
      - ls-users-network

networks:
  ls-users-network:
    driver: bridge

volumes:
  postgres-data:
